AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/initializers/forbidden_yaml.rb
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/
  DisplayCopNames: true
  DisplayStyleGuide: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
  Exclude:
    - test/action_controller/serialization_test.rb

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/AbcSize:
  Max: 35 # TODO: Lower to 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 261 # TODO: Lower to 100

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Max: 110 # TODO: Lower to 80

Metrics/MethodLength:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MissingElse:
  Enabled: false # TODO: maybe enable this?
  EnforcedStyle: case

Style/EmptyElse:
  EnforcedStyle: empty

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Naming/PredicateName:
  Enabled: false # TODO: enable with correct prefixes

Style/ClassVars:
  Enabled: false
