# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edad385abe8ffcfc54c5505f038478c8dc256327ec8cfe2da323d8172bae4a428b79a3adeb7efd5212a3723c4ac54cbcf111ec793347d0ae5e3b3665460ab13b

test:
  secret_key_base: 3b7cbb8265d536313bbb6a957eb6c7c534f63669202aa0ec7dd0ea33d92fee8126d659e3a9984704578831bda40118a3efde8b4fb7355f8ea6a28e398595ed64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
