# frozen_string_literal: true
# source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
version = ENV['RAILS_VERSION'] || '5.0'

if version == 'master'
  gem 'rails', github: 'rails/rails'
else
  gem 'rails', "~> #{version}.0"
end

# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
